export ASOFTREF=$PWD/libs
export FOOTMAIN=$PWD
export FOOTREF=$ASOFTREF/src
export FOOTLEVEL0=$FOOTMAIN/Reconstruction/level0
export FOOTCONFIG=$FOOTLEVEL0/config
export FOOTRES=$FOOTLEVEL0/results
export FOOTSIMU=$FOOTMAIN/Simulation

export LD_LIBRARY_PATH=$ROOTSYS/lib:./:$ASOFTREF/lib:$ASOFTREF/src/TABMbase:$ASOFTREF/src/TAGbase:$ASOFTREF/src/TAGfoot:$ASOFTREF/src/TAGmclib:$ASOFTREF/src/TAIRbase:$ASOFTREF/src/TAVTbase:$ASOFTREF/src/TAITbase:$ASOFTREF/src/TADCbase:$ASOFTREF/src/TACAbase:$ASOFTREF/src/TATWbase:$ASOFTREF/GenFit/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:./:$ASOFTREF/lib:$ASOFTREF/src/TABMbase:$ASOFTREF/src/TAGbase:$ASOFTREF/src/TAGfoot:$ASOFTREF/src/TAGmclib:$ASOFTREF/src/TAIRbase:$ASOFTREF/src/TAVTbase:$ASOFTREF/src/TAITbase:$ASOFTREF/src/TADCbase:$ASOFTREF/src/TACAbase:$ASOFTREF/src/TATWbase:$ASOFTREF/GenFit/lib
