#ifndef _EVENT_STRUCT_HH
#define _EVENT_STRUCT_HH


const int MAXCROSS = 10000;
const int MAXNUMP = 1000;
const int MAXSC = 200;
const int MAX1DC = 500;
const int MAXVTX = 200;
const int MAX2DC = 500;
const int MAXSCINT = 1000;
const int MAXCRY = 2000;

typedef struct {
  Int_t EventNumber;
  Int_t trn;
  Int_t trid[MAXNUMP];
  Int_t trgen[MAXNUMP];
  Int_t trcha[MAXNUMP];
  Int_t trreg[MAXNUMP];
  Int_t trbar[MAXNUMP];
  Int_t trdead[MAXNUMP];
  Int_t trpaid[MAXNUMP];
  Double_t trix[MAXNUMP];
  Double_t triy[MAXNUMP];
  Double_t triz[MAXNUMP];
  Double_t trfx[MAXNUMP];
  Double_t trfy[MAXNUMP];
  Double_t trfz[MAXNUMP];
  Double_t tripx[MAXNUMP];
  Double_t tripy[MAXNUMP];
  Double_t tripz[MAXNUMP];
  Double_t trfpx[MAXNUMP];
  Double_t trfpy[MAXNUMP];
  Double_t trfpz[MAXNUMP];
  Double_t trmass[MAXNUMP];
  Double_t trtime[MAXNUMP];
  Double_t tof[MAXNUMP];
  Double_t trlen[MAXNUMP];
  
  Int_t stn;
  Int_t stid[MAXSC];
  Double_t stinx[MAXSC];
  Double_t stiny[MAXSC];
  Double_t stinz[MAXSC];
  Double_t stoutx[MAXSC];
  Double_t stouty[MAXSC];
  Double_t stoutz[MAXSC];
  Double_t stinpx[MAXSC];
  Double_t stinpy[MAXSC];
  Double_t stinpz[MAXSC];
  Double_t stoutpx[MAXSC];
  Double_t stoutpy[MAXSC];
  Double_t stoutpz[MAXSC];
  Double_t stde[MAXSC];
  Double_t stal[MAXSC];
  Double_t sttim[MAXSC];

  Int_t nmon;
  Int_t idmon[MAX1DC];
  Int_t ilayer[MAX1DC];
  Int_t icell[MAX1DC];
  Int_t iview[MAX1DC];
  Double_t xinmon[MAX1DC];
  Double_t yinmon[MAX1DC];
  Double_t zinmon[MAX1DC];
  Double_t xoutmon[MAX1DC];
  Double_t youtmon[MAX1DC];
  Double_t zoutmon[MAX1DC];
  Double_t pxinmon[MAX1DC];
  Double_t pyinmon[MAX1DC];
  Double_t pzinmon[MAX1DC];
  Double_t pxoutmon[MAX1DC];
  Double_t pyoutmon[MAX1DC];
  Double_t pzoutmon[MAX1DC];
  Double_t demon[MAX1DC];
  Double_t almon[MAX1DC];
  Double_t timmon[MAX1DC];

  Int_t nvtx;
  Int_t idvtx[MAXVTX];
  Int_t iplavtx[MAXVTX];
  Int_t irowvtx[MAXVTX];
  Int_t icolvtx[MAXVTX];
  Double_t xinvtx[MAXVTX];
  Double_t yinvtx[MAXVTX];
  Double_t zinvtx[MAXVTX];
  Double_t xoutvtx[MAXVTX];
  Double_t youtvtx[MAXVTX];
  Double_t zoutvtx[MAXVTX];
  Double_t pxinvtx[MAXVTX];
  Double_t pyinvtx[MAXVTX];
  Double_t pzinvtx[MAXVTX];
  Double_t pxoutvtx[MAXVTX];
  Double_t pyoutvtx[MAXVTX];
  Double_t pzoutvtx[MAXVTX];
  Double_t devtx[MAXVTX];
  Double_t alvtx[MAXVTX];
  Double_t timvtx[MAXVTX];

  Int_t n2dc;
  Int_t id2dc[MAX2DC];
  Int_t ipla2dc[MAX2DC];
  Int_t icell2dc[MAX2DC];
  Int_t iview2dc[MAX2DC];
  Double_t xin2dc[MAX2DC];
  Double_t yin2dc[MAX2DC];
  Double_t zin2dc[MAX2DC];
  Double_t xout2dc[MAX2DC];
  Double_t yout2dc[MAX2DC];
  Double_t zout2dc[MAX2DC];
  Double_t pxin2dc[MAX2DC];
  Double_t pyin2dc[MAX2DC];
  Double_t pzin2dc[MAX2DC];
  Double_t pxout2dc[MAX2DC];
  Double_t pyout2dc[MAX2DC];
  Double_t pzout2dc[MAX2DC];
  Double_t de2dc[MAX2DC];
  Double_t al2dc[MAX2DC];
  Double_t tim2dc[MAX2DC];

  Int_t nscint;
  Int_t idscint[MAXSCINT];
  Int_t irowscint[MAXSCINT];
  Int_t icolscint[MAXSCINT];
  Double_t xinscint[MAXSCINT];
  Double_t yinscint[MAXSCINT];
  Double_t zinscint[MAXSCINT];
  Double_t xoutscint[MAXSCINT];
  Double_t youtscint[MAXSCINT];
  Double_t zoutscint[MAXSCINT];
  Double_t pxinscint[MAXSCINT];
  Double_t pyinscint[MAXSCINT];
  Double_t pzinscint[MAXSCINT];
  Double_t pxoutscint[MAXSCINT];
  Double_t pyoutscint[MAXSCINT];
  Double_t pzoutscint[MAXSCINT];
  Double_t descint[MAXSCINT];
  Double_t alscint[MAXSCINT];
  Double_t timscint[MAXSCINT];

  Int_t ncry;
  Int_t idcry[MAXCRY];
  Int_t irowcry[MAXCRY];
  Int_t icolcry[MAXCRY];
  Double_t xincry[MAXCRY];
  Double_t yincry[MAXCRY];
  Double_t zincry[MAXCRY];
  Double_t xoutcry[MAXCRY];
  Double_t youtcry[MAXCRY];
  Double_t zoutcry[MAXCRY];
  Double_t pxincry[MAXCRY];
  Double_t pyincry[MAXCRY];
  Double_t pzincry[MAXCRY];
  Double_t pxoutcry[MAXCRY];
  Double_t pyoutcry[MAXCRY];
  Double_t pzoutcry[MAXCRY];
  Double_t decry[MAXCRY];
  Double_t alcry[MAXCRY];
  Double_t timcry[MAXCRY];
  
  Int_t ncross;
  Int_t idcross[MAXCROSS];
  Int_t nregcross[MAXCROSS];
  Int_t nregoldcross[MAXCROSS];
  Double_t xcross[MAXCROSS];
  Double_t ycross[MAXCROSS];
  Double_t zcross[MAXCROSS];
  Double_t pxcross[MAXCROSS];
  Double_t pycross[MAXCROSS];
  Double_t pzcross[MAXCROSS];
  Double_t mcross[MAXCROSS];
  Double_t chcross[MAXCROSS];
  Double_t tcross[MAXCROSS];

} EVENT_STRUCT;

#endif
